CREATE TABLE `profiles` (
    `id` INT(8) UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    `uuid` VARCHAR(255) NOT NULL,
    `experience` BIGINT UNSIGNED NOT NULL DEFAULT '0',
    `level` INT(8) UNSIGNED NOT NULL DEFAULT '1',
    `total_score` BIGINT UNSIGNED NOT NULL DEFAULT '0',
    `play_count` INT(7) UNSIGNED NOT NULL DEFAULT '0',
    `mastery` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `performance_rating` BIGINT UNSIGNED NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`)
)
