pkg = "static"
dest = "src/static/"
fmt = false
tags = "" # build tags

[compression]
    compress = false

    # valid values are:
    # -> "NoCompression"
    # -> "BestSpeed"
    # -> "BestCompression"
    # -> "DefaultCompression" or ""
    method = ""

    # do we automatically decompress at runtime, false = decompress at runtime
    keep = false

clean = false
output = "migrations.go"
unexporTed = false
spread = false
lcf = true
debug = false

[[custom]]
    files = ["src/database/migrations/000_table.sql"]
    base = "src/database/migrations/"
    prefix = ""
    tags = ""
