version: 2.1

jobs:
    docker:
    steps:
        - checkout
        - run:
            name: Build
            command: |
                docker build -t $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/profiles:$(date +%Y.%m.%H%M%S) .