version: 2.1

executors:
  docker:
    working_directory: /tmp/workspace
    docker:
      - image: docker:latest

jobs:
    docker:
        executor: docker
        steps:
            - checkout
            - run:
                name: Build
                command: |
                    docker build -t $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/profiles:$(date +%Y.%m.%H%M%S) .

workflows:
    version: 2
    build:
        jobs:
            - docker